### ISSUE TITLE
User Object not updated on leaving group

### ISSUE THREAD

**Issue by Plsr** [timomeh/WBA2SS15AfshariPoplawskiMaemecke#12]
If a user leaves a Group, the group object is updated properly (and thus is displayed correctly in the frontend) but the user object is not updated at all.

This currently leads to a situation where I cannot check if a user is in a group and can create an event or not. I'll see if I can fix it.

**Comment by timomeh** [comment]
Yeah, the group program-logic is currently not linked with the user program-logic.
