### ISSUE TITLE
Split up RouteMap.js in frontend?

### ISSUE THREAD

**Issue by Plsr** [timomeh/WBA2SS15AfshariPoplawskiMaemecke#2]
I think we should split the RoutMap up in our three (or four, with login) different routes, like we did in the server.
Right now, we only have seven routes in it and it is pretty big already.

**Comment by timomeh** [comment]
Joup.

-- 
Timo Mämecke
Front End Developer @ 51seven
m: +49.163.7431993

Wiesenstraße 18
51643 Gummersbach

On 23 Jun 2015 at 08:49:45, Christian Poplawski (notifications@github.com) wrote:

I think we should split the RoutMap up in our three (or four, with login) different routes, like we did in the server.
Right now, we only have seven routes in it and it is pretty big already.

**Comment by timomeh** [comment]
Closed via 842c18e454b78bf29fc0179a1060260184d21904
